### ISSUE TITLE
Not enough contract on menu

### ISSUE THREAD

**Issue by Serhioromano** [phil-harmoniq/arc-plus#7]
I like this theme and use it every day, but I have one thing that annoy me. I write in Markdown and when I use spelling and call suggestion menu it is very hard to see which element is highlighted. 

![2020-01-02_12-56-34](https://user-images.githubusercontent.com/650741/71655087-710c5c80-2d5f-11ea-8402-a51920d84316.png)

You can barely see in in perfect lighting conditions but in all other cases I cannot see it at all. I have to click arrow up and down few times until I see the difference.

**Comment by phil-harmoniq** [comment]
Hey, thanks for pointing this out! I have tweaked the selection color to stand out more and published a new version to the extension marketplace.

**Comment by Serhioromano** [comment]
So good.
